### ISSUE TITLE
Central 1.2.009 not working on Ubuntu Docker 

### ISSUE THREAD

**Issue by nunocgoncalves** [CorefluxCommunity/coreflux-central#2]
### Describe the bug 🐞

When running Central on Docker, the console outputs:
```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CachedCulturesByName()
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateHostingEnvironment(Microsoft.Extensions.Configuration.IConfiguration)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(Microsoft.Extensions.Hosting.HostApplicationBuilderSettings)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(Microsoft.AspNetCore.Builder.WebApplicationOptions, System.Action`1<Microsoft.Extensions.Hosting.IHostBuilder>)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(System.String[])
   at Program.<Main>$(System.String[])
```

### To Reproduce 🔄

1. Build the below Docker image with ``docker build . -t 1.2.009``:
```Dockerfile
FROM ubuntu:latest

# Update package lists and install dependencies
RUN apt-get update \
    && apt-get install -y curl unzip \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Add your CorefluxCentral download URL here
ARG COREFLUX_DOWNLOAD_URL=https://downloads.coreflux.org/CorefluxCentral-linux-x64-v-1-2-009.zip

# Download and unzip the CorefluxCentral file
RUN curl -L ${COREFLUX_DOWNLOAD_URL} -o CorefluxCentral.zip \
    && unzip CorefluxCentral.zip \
    && chmod +x CorefluxCentral \
    && rm CorefluxCentral.zip

# Expose the MQTT port
EXPOSE 1883

# Command to run the CorefluxCentral broker
CMD ["./CorefluxCentral"]
```
2. Run  with ``docker run -p 1883 1.2.009``

### Expected behavior ✅

After the Docker image is built, the container should start.

### Environment 🌐

Ubuntu 22.04 LTS (Jammy Jellyfish)

### Additional Info ➕

Ubuntu Docker Image with tag [``latest``](https://hub.docker.com/layers/library/ubuntu/latest/images/sha256-c9cf959fd83770dfdefd8fb42cfef0761432af36a764c077aed54bbc5bb25368?context=explore)

### Terms of Service

- [X] I agree

**Comment by nunocgoncalves** [comment]
It turns out Ubuntu is missing a critical dotnet dependency. Using the [``bitnami/dotnet``](https://hub.docker.com/r/bitnami/dotnet) Docker image solved the issue.
